export const REQUEST_API_DATA = 'REQUEST_API_DATA';
export const RECEIVE_API_DATA = 'RECEIVE_API_DATA';

export const REQUEST_API_DATA_BY_ID = 'REQUEST_API_DATA_BY_ID';
export const RECEIVE_API_DATA_BY_ID = 'RECEIVE_API_DATA_BY_ID';

export const REQUEST_CREATE_EMPLOYEE = 'REQUEST_CREATE_EMPLOYEE';
export const RECIEVE_CREATE_EMPLOYEE = 'RECIEVE_CREATE_EMPLOYEE';

export const REQUEST_UPDATE_USER_DATA = 'REQUEST_UPDATE_USER_DATA';
export const RECIEVE_UPDATE_USER_DATA = 'RECIEVE_UPDATE_USER_DATA';
